config/routes.rb
Rails.application.routes.draw do
  resources :comments
  # Player routing
  devise_for :players, :controllers => { registrations: 'registrations' } # Use custom registrations controller for custom devise fields
  # Game routing
  resources :games, param: :slug do
    get :autocomplete_tag_name, :on => :collection
  end

  # Tag routing
  resources :tags, only: [:index, :show]

  # Difficulty routing
  resources :difficulty, param: :name

  # Types routing
  resources :types, param: :name

  # Contact routing
  resources :contacts, only: [:new, :create]

  # Users routing
  get "/players/:username", to: "players#show", as: "show_player"

  resource :players do
    resource :avatar do
      match '/delete_avatar', to: 'players#delete_avatar', via: 'delete'
    end
  end

  # Pages routing
  get "/contact" => "contacts#new"
  get "/difficulties" => "difficulty#index"
  get "/:page" => "pages#show"

  # Set root path
  root :to => "pages#show", :page => 'home'
end

app/views/partials/_add-comment.html.erb
<% if current_player %><% comment_build = current_player.comments.build ; picture = current_player.avatar.attached? ? current_player.avatar : "profile_image.png" %><% else %><% comment_build = Comment.new ; picture = "profile_image.png"%><% end %>
<div class="row" style="margin-top: 5px">
    <div class="col-sm-2 my-auto">
        <%= image_tag(picture, :size => "50x50", :class => "border border-primary rounded-circle profile_image") %>
    </div>
    <%= form_for(comment_build, :html => {:class => "col-sm-10 row" }) do |f| -%>
    <div class="field form-group col-sm-10 my-auto">
        <%= f.text_field :content, class: "form-control border border-primary rounded" %>
    </div>

    <div class="actions col-sm-2 my-auto">
        <%= f.hidden_field :game_id, value: @game.id %>
        <%= f.submit "Comment", class: "btn btn-outline-light", style: "background-color: white" %>
    </div>
<% end %>
</div>

app/views/partials/_changelog.html.erb
<% @game.versions.reverse.each do |version| %>
<% player = Player.find(version.whodunnit) -%>
<p><%= link_to player.username, show_player_url(player.username) %> performed <%= version.event %> at <%= version.created_at %></p>
<% end %>

app/views/partials/_comments.html.erb
<div class="row comment-box"> 
    <div class="col-sm-2">
    </div>
    <div class="col-sm-8">
        <br />
        <%= render 'partials/add-comment' %>

        <% comments = Comment.where(:game_id => @game.id) %>
        <% comments.each do |comment| -%>
            <% player = Player.find(comment.player_id) -%>
            <div class="row content comment border border-primary rounded">
                <div class="col-sm-2 text-center comment-inner">
                    <span><%= link_to( image_tag(player.avatar.attached? ? player.avatar : "profile_image.png", :size => "50x50", :alt => player.username, :class => "border border-primary rounded-circle profile_image"), show_player_url(player.username)) %><br /><%= link_to( player.display_name? ? player.display_name : player.username, show_player_url(player.username)) %></span>
                </div>
                <div class="col-sm-10 text-left comment-inner">
                    <p><%= comment.content %></p>
                    <p class="comment-data"><i><%= comment.created_at.strftime("%F %T") %></i><% if current_player && player.username == current_player.username %><span style="float:right;"><%= link_to content_tag(:i, nil, class: 'fa fa-lg fa-trash'), comment, method: :delete, data: { confirm: 'Are you sure you want to delete this comment?' } %></span><% end %></p>
                </div>
            </div>
        <% end -%>
    </div>
    <div class="col-sm-2">
    </div>
</div>

app/views/partials/_feed.html.erb
<div class="row container">
<h2>Recent Activity</h2>
<br />
<% activity_map = { 'tag_list' => 'Tags', 'name_alt' => 'Alternative Names' } %>
<% @feed.each do |item| %>
    <% player = Player.find(item['player_id']) ; game = Game.find(item['game_id']) ; item.key?('event') ? '' : item['event'] = "commented on" %>
    <div class="row container">
        <div class="col-sm-1">
            <span><%= link_to( image_tag(player.avatar.attached? ? player.avatar : "profile_image.png", :size => "50x50", :alt => player.username, :class => "border border-primary rounded-circle profile_image"), show_player_url(player.username)) %></span>
        </div>
        <div class="col-sm-10">
            <p><b><%= link_to player.username, show_player_url(player.username) %></b> <%= item['event'].sub(/e$/, 'ed') %> <%= link_to word_cap(game.name), game_path(game.slug) %> at <i><%= item['updated_at'] || item['created_at'] %></i></p>
            <% if item['event'] == "commented on" %>
                <blockquote class="blockquote border-primary border-left"><p><%= truncate(strip_tags(item['content'].html_safe), :length => 100, :omission => "... (continued)") %></p></blockquote>
            <% elsif item['event'] == "create" %>
                <% text = item['content'].tr('-', '') %>
                <% yaml = YAML.load(item['content']) %>
                <blockquote class="blockquote border-primary border-left"><p><%= truncate(strip_tags(yaml['description'][1]), :length => 100, :omission => "... (continued)") %></p></blockquote>
            <% else %>
                <% yaml = YAML.load(item['content']) %>
                <% yaml.delete('updated_at') %>
                <% yaml.keys.each { |k| yaml[ activity_map[k] ] = yaml.delete(k) if activity_map[k]} %>
                <blockquote class="blockquote border-primary border-left"><p>Made changes to <i><%= word_cap(yaml.keys.join(', ')) %></i></p></blockquote>
            <% end %>
            <br />
        </div>
        <div class="col-sm-1">
        </div>
    </div>
<% end %>
</div>

app/views/partials/_footer.html.erb
<footer class="page-footer font-small cyan darken-3">
  <div class="container">
    <div class="row">
      <div class="col-md-12 pt-5 pb-3">
        <div class="mb-3 text-center">
          <a href="https://facebook.com/improvgamesfun" class="socialicon fab fa-lg fa-facebook fa-2x"></a>
          <a href="https://twitter.com/ImprovGamesFun" class="socialicon fab fa-lg fa-twitter fa-2x"></a>
          <a href="https://ko-fi.com/stuuuts" class="socialicon fa fa-lg fa-coffee fa-2x"></a>
          <a href='https://www.patreon.com/stuts' class="socialicon fab fa-lg fa-patreon fa-2x" ></a>
        </div>
        <div class="mb-1 text-center">
            <p style="color: white"><a href="/">Home</a> | <a href="/about">About</a> | <a href="/games">Games</a> | <a href="/contact">Contact</a></p>
        </div>
      </div>
    </div>
  </div>

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">© 2019 Copyright:
    <a href="https://www.improvgames.fun"> ImprovGames.Fun</a>
  </div>
  <!-- Copyright -->

</footer>

app/views/partials/_game-form.html.erb
    <div class="field form-group">
        <%= f.label :name_alt, 'Other Names (comma-separated list of alternative names for this game)' %>
        <%= f.text_field :name_alt, class: "form-control" %>
    </div>

    <div class="field form-group">
        <%= f.label :difficulty_id, 'Difficulty' %>
        <%= collection_select :game, :difficulty_id, Difficulty.all, :id, :name_in_caps, {}, {:class=>"form-control", :required => true} %>
    </div>

    <div class="field form-group">
        <%= f.label :type_id, 'Type' %>
        <%= collection_select :game, :type_id, Type.all, :id, :name_in_caps, {}, {:class=>"form-control", :required => true} %>
    </div>

    <div class="field form-group">
        <%= f.label :players_min, 'Minimum Players' %>
        <%= f.number_field :players_min, class: "form-control", required: true %>
    </div>

    <div class="field form-group">
        <%= f.label :players_max, 'Maximum Players' %>
        <%= f.number_field :players_max, class: "form-control", required: true %>
    </div>

    <div class="field form-group">
        <%= f.label :description, 'Description (how to play the game)' %>
        <%= f.trix_editor :description, class: "form-control", id: "description", required: true %>
    </div>

    <div class="field form-group">
        <%= f.label :intro, 'Intro (tips on introducing and playing the game in a show format)' %>
        <%= f.trix_editor :intro, class: "form-control" %>
    </div>

    <div class="field form-group">
        <%= f.label :notes %>
        <%= f.trix_editor :notes, class: "form-control" %>
    </div>

    <div class="field form-group">
        <%= f.label :sample, 'Sample (link to a YouTube video)' %>
        <%= f.text_field :sample, class: "form-control" %>
    </div>

    <div class="field form-group">
        <%= f.label :tag_list, 'Tags (comma-separated list of tags)' %>
        <%= f.autocomplete_field :tag_list, autocomplete_tag_name_games_path, :"data-delimiter" => ', ', :value => @game.tag_list.join(', '), 'data-showNoMatches' => false, class: "form-control" %>
    </div>
    <br />

    <div class="actions">
        <%= f.submit @submit_text, class: "btn btn-outline-light" %>
    </div>

app/views/partials/_game-list.html.erb
<ul class="nav nav-tabs" id="myTab" role="tablist">
    <% ('A'..'Z').each do |letter| %>
    <li class="nav-item">
        <a class="nav-link <%= "active" if letter == 'A'%>" id="<%= letter %>-tab" data-toggle="tab" href="#<%= letter %>" role="tab" aria-controls="<%= letter %>" aria-selected="true"><%= letter %></a>
    </li>
    <% end %>
</ul>
<div class="tab-content" id="myTabContent">
<% games = Game.all %>
<% ('A'..'Z').each do |letter| %>
    <% @games = games.where('name LIKE ?', letter + '%').all.order('name') %>
    <div class="tab-pane fad show <%= "active" if letter == 'A'%>" href="<%= letter %>" id="<%= letter %>" role="tabpanel" aria-labelledby="<%= letter %>-tab">
    <br />
    <% unless @games.empty? %>
        <%= render 'partials/game-table' %>
    <% else %>
        <p>No games starting with <%= letter %>!</p>
    <% end %>
    </div>
<% end %>
</div>
<%= javascript_tag "tabLinks()" %>

app/views/partials/_game-table.html.erb
<div class="table-responsive">
<table class="table table-hover" style="display:table">
    <thead class="thead-dark">
        <tr scope="col"  style="text-align:center;font-size: large;line-height: 1;">
            <th class="align-middle">Name</th>
            <th class="align-middle hidemobile">Players (Min)</th>
            <th class="align-middle hidemobile">Players (Max)</th>
            <th class="align middle">Difficulty</th>
            <th class="align-middle">Tags</th>
        </tr>
    </thead>
    <% unless @games.empty? %>
    <% @games.each do |game| %>
    <tr scope="row" style="text-align:center">
        <td class="align-middle"><%= link_to word_cap(game.name), game_path(game) %></td>
        <td class="align-middle hidemobile"><%= game.players_min %></td>
        <td class="align-middle hidemobile"><%= game.players_max %></td>
        <td class="align middle"><%= diff = find_difficulty(game.difficulty_id) ; link_to word_cap(diff.name), difficulty_path(diff.name) %></td>
        <td class="align-middle"><%= game.tag_list.map {|t| link_to word_cap(t), tag_path(t)}.join(", ").html_safe %></td>
    </tr>
    <% end -%>
    <% end -%>
</table>
</div>

app/views/partials/_nav-item.html.erb
<li class="nav-item <%= 'active' if current_page?("/#{page}") %>">
    <a class="nav-link" href="/<%= page %>"><%= word_cap(page) %></a>
</li>

app/views/partials/_player-badges.html.erb
<% tags = [] %>
<% if @player.username == 'stuts' %><% tags << 'Founder' %><% end %>
<% if @creations >= 10 %><% tags << 'Creator' %><% end %>
<% if @contributions >= 10 %><% tags << 'Contributor' %><% end %>

<% tags.each do |tag| %>
    <span class="badge badge-light"><%= tag %></span>
<% end %>

app/views/partials/_player-socials.html.erb
<% socials = ['facebook', 'twitter', 'instagram', 'youtube', 'website'] %>

<% socials.each do |social| %>
    <% icon = social %>
    <% unless @player[social].nil? || @player[social].empty?%>
        <%= sociallink(social, @player[social]) %>
    <% end %>
<% end %>

app/views/partials/_social-buttons.html.erb
<%= render partial: 'partials/socialicon', locals: {object: socialicon('facebook')} %>
<%= render partial: 'partials/socialicon', locals: {object: socialicon('twitter', "Check out the improv game #{ERB::Util.u(word_cap(@game.name))}!", "improvgamesfun, improv, games")} %>
<%= render partial: 'partials/socialicon', locals: {object: socialicon('tumblr', "Check out the improv game #{ERB::Util.u(word_cap(@game.name))}!", "improvgamesfun, improv, games")} %>
<%= render partial: 'partials/socialicon', locals: {object: socialicon('reddit', "Check out the improv game #{ERB::Util.u(word_cap(@game.name))}!")} %>
<%= render partial: 'partials/socialicon', locals: {object: socialicon('envelope', "Check out the improv game #{ERB::Util.u(word_cap(@game.name))}!")} %>

app/views/partials/_socialicon.html.erb
<a rel="nofollow" data-site="<%= object[:name] %>" title="Share to <%= word_cap(object[:name]) %>" class="socialicon fa<%unless object[:name] == 'envelope'%>b<%end%> fa-lg fa-<%= object[:name] %>" href="JavaScript:newPopup('<%= object[:href] %>')" target="external"></a>

app/views/partials/_sub-header.html.erb
<sub-header>
    <nav class="navbar navbar-expand-md navbar-dark">
        <%# LEFT ALIGNED %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarMenu">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarMenu">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="/feed">Activity Feed</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/contact">Contact Us</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="subDropdownGames" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Games
                    </a>
                    <div class="dropdown-menu dropdown-menu-sub" aria-labelledby="subDropdownGames">
                        <a class="dropdown-item dropdown-item-sub" href="/games">All</a>
                        <a class="dropdown-item dropdown-item-sub" href="/games/new">Create</a>
                        <a class="dropdown-item dropdown-item-sub" href="/difficulties">Difficulties</a>
                        <a class="dropdown-item dropdown-item-sub" href="/tags">Tags</a>
                        <a class="dropdown-item dropdown-item-sub" href="/types">Types</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="subDropdownInfo" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Project
                    </a>
                    <div class="dropdown-menu dropdown-menu-sub" aria-labelledby="subDropdownInfo">
                        <a class="dropdown-item dropdown-item-sub" href="/about">About</a>
                        <a class="dropdown-item dropdown-item-sub" href="/get_involved">Get Involved</a>
                        <a class="dropdown-item dropdown-item-sub" href="/roadmap">Roadmap</a>
                    </div>
                </li>
            </ul>
        <%# RIGHT ALIGNED %>
            <ul class="navbar-nav ml-auto">
                <%=form_tag('/search', :method => "get", id: "search-form", class: 'form-inline') do %>
                    <%= text_field_tag :search, params[:search], placeholder: "Search...", class: 'form-control' %>
                    <button class="btn btn-outline-light fa fa-search" type="submit"></button>
                <% end %>
            </ul>
        </div>
    </nav>
</sub-header>