config/routes.rb
Rails.application.routes.draw do
  resources :comments
  # Player routing
  devise_for :players, :controllers => { registrations: 'registrations' } # Use custom registrations controller for custom devise fields
  # Game routing
  resources :games, param: :slug do
    get :autocomplete_tag_name, :on => :collection
  end

  # Tag routing
  resources :tags, only: [:index, :show]

  # Difficulty routing
  resources :difficulty, param: :name

  # Types routing
  resources :types, param: :name

  # Contact routing
  resources :contacts, only: [:new, :create]

  # Users routing
  get "/players/:username", to: "players#show", as: "show_player"

  resource :players do
    resource :avatar do
      match '/delete_avatar', to: 'players#delete_avatar', via: 'delete'
    end
  end

  # Pages routing
  get "/contact" => "contacts#new"
  get "/difficulties" => "difficulty#index"
  get "/:page" => "pages#show"

  # Set root path
  root :to => "pages#show", :page => 'home'
end

app/views/pages/about.html.erb
<h2>The Aim</h2>
<p>This site is built with the intention of collecting all of the weird and wonderful improvisation games into a single wiki. Also to build a community around developing and sharing new games with fellow improvisers!</p>
<p>The idea originated after an improv workshop along with the teacher, <i>Tom Young</i>. We were talking about his array of game notes in various locations and my want to database the s**t out of them.</p>
<p>From the initial idea, I have since scribbled, noted and planned many other features for this site that I believe will both connect and aid the improv community as a whole. For a taste of things to come, check out the <%= link_to 'roadmap', '/roadmap' %>.</p>
<hr>
<h2>The Games</h2>
<p>Improv games have always been tweaked, modified and passed around between teachers and students alike. While there is no
such thing as 'owning' an improv game there is certainly credit due for the writing of the descriptions and rules of a game.</p>
<p>This site emphasises this point with collaborative editing of games such that we can all contribute our thoughts, notes and details to the games we hold so near and dear to our hearts.</p>
<hr>
<h2>The Community</h2>
<p>Without the community, this site will neither survive nor thrive. There are already some wonderfully active users but the more the merrier!</p>
<p>Some members of the community have specially contributed to the development of this site, either through help with marketing, design or structure. I'd like to give them a special shoutout here:</p>
<ul>
    <li><a href="https://twitter.com/mobilehugh">Hugh Macleod</a> provided some really useful insight into categorising games</li>
    <li><a href="https://twitter.com/boostimprov">The Improv Boost</a> helped spread the word and taught me a lot regarding social media presence</li>
</ul>
<p>And a special thanks to all who reached out to send over game notes, feature requests or just to compliment the site. Please do <a href="/contact">get in touch</a> if you have anything you'd like to say!</p>

app/views/pages/feed.html.erb
<%= render 'partials/feed' %>

app/views/pages/get_involved.html.erb
<h2>Get Involved</h2>
<p>Thanks for wanting to get involved with the development of ImprovGames.Fun! Any and all help is greatly appreciated.</p>
<p>Things you can do to support the growth of this community:</p>
<ul>
    <li>Contribute games!</li>
    <li>Leave us a good review on <a target="_blank" rel="noopener noreferrer" href="https://fb.me/improvgamesfun">Facebook</a></li>
    <li>Spread the word to fellow improvisers</li>
    <li>Financially support the hosting and development of this website (<a target="_blank" rel="noopener noreferrer" href="https://www.ko-fi.com/stuuuts">Support Me on Ko-Fi</a>, <a target="_blank" rel="noopener noreferrer" href="https://www.patreon.com/stuts">Become a Patron</a> or <a target="_blank" rel="noopener noreferrer" href="https://www.redbubble.com/people/-stuts-/works/36254011-improv-games-fun">Purchase Some Merchandise</a>)</li>
    <li>Assist with development of features and fixes (COMING SOON)</li>
</ul>
<p>Alternatively, if you have any questions, feedback or just want to chat then feel free to <a href="/contact">get in touch</a>.</p>

app/views/pages/home.html.erb
<h2 style="text-align: center">Welcome to ImprovGames.Fun!</h2>
<h4 style="text-align: center"><i>The Ultimate Improv Game Wiki</i></h4>
<br>
<p style="text-align: center">ImprovGames.Fun is a community wiki project for improvisers to share and discover improv games with one another. A collaborative project to centralise all of the mad games that get played all around the globe.<p>
<p style="text-align: center">What are you waiting for?? Find out <%= link_to "more about us", '/about' %>, check out the <%= link_to "games we have", games_path %> and see how <%= link_to "you can get involved", '/get_involved' %>!</p>
<hr>
<div class="container-fluid text-center">
    <div class="row content">
        <div class="col-sm-4">
            <h2 style="text-align: center"><%= @game_count %></h2>
            <h3 style="text-align: center">Games</h3>
        </div>
        <div class="col-sm-4">
            <h2 style="text-align: center"><%= @tag_count %></h2>
            <h3 style="text-align: center">Tags</h3>
        </div>
        <div class="col-sm-4">
            <h2 style="text-align: center"><%= @player_count %></h2>
            <h3 style="text-align: center">Players</h3>
        </div>
    </div>
    <br >
    <p style="text-align: center">Jump in, be a part of it and help us grow!</p>
</div>
<hr>
<br >
<h3 style="text-align: center">Have you played...</h3>
<br >
<div class="border border-primary rounded">
<h3 style="text-align: center"><i><% game = Game.order(Arel.sql("RANDOM()")).first %><%=link_to word_cap(game.name), game_path(game)  %></i></h3>
<blockquote class="blockquote text-center border-top border-primary rounded"><p><%= game.description.html_safe %></p></blockquote>
</div>
<br />
<hr>
<%= render 'partials/feed' %>

app/views/pages/roadmap.html.erb
<h2>Roadmap</h2>

<p>This site is still in early development stages. While the core functionality for users and games has been added there are a bunch of features that I'd like to get implemented going forward.</p>

<p>A look at upcoming planned features:</p>
<ul>
    <li>Translations (to ensure that this tool can benefit improvisers all over the world)</li>
    <li>Voting systems (to better allow the community to curate the quality content on the site)</li>
    <li>Game collections (organise and save games all in one place)</li>
    <li>Game exports (export your collections of games to a printable document)</li>
    <li>Groups (create your improv troupe, add members and feature your own group content)</li>
    <li>Comments and discussion support on games (to promote the evolution and analysis of various games)</li>
    <li>Community reputation (to reflect contributions to content and discussion on the site)</li>
    <li>Improv tools (various helper tools for rehearsals and workshops)</li>
    <ul>
        <li>Random suggestions</li>
        <li>Workshop/setlist builder</li>
    </ul>
</ul>
<p>Phew. Well. The above is a dauntingly ambitious roadmap but I'm determined to create the ultimate improv companion tool. Time to locate the elbow grease...</p>
<p>Be sure to check out how you can <a href="/get_involved">Get Involved</a> in making this dream a reality.</p>

app/views/pages/search.html.erb
<h1>Results</h1>
<% if ! defined? @results %>
    <p>Welcome to the search page, to search for something use the search bar at the top of the page.</p>
<% elsif @results.empty? %>
    <p>No games matching: <%= params[:search] %></p>
<% else %>
    <% @results.each do |result| %>
        <h2><%= link_to word_cap(result.searchable.name), result.searchable %></h2>
        <p><%= truncate(strip_tags(result.searchable.description.html_safe), :length => 100, :omission => "... (continued)") %> <p>
        <hr >
    <% end %>
<% end %>