config/routes.rb
Rails.application.routes.draw do
  resources :comments
  # Player routing
  devise_for :players, :controllers => { registrations: 'registrations' } # Use custom registrations controller for custom devise fields
  # Game routing
  resources :games, param: :slug do
    get :autocomplete_tag_name, :on => :collection
  end

  # Tag routing
  resources :tags, only: [:index, :show]

  # Difficulty routing
  resources :difficulty, param: :name

  # Types routing
  resources :types, param: :name

  # Contact routing
  resources :contacts, only: [:new, :create]

  # Users routing
  get "/players/:username", to: "players#show", as: "show_player"

  resource :players do
    resource :avatar do
      match '/delete_avatar', to: 'players#delete_avatar', via: 'delete'
    end
  end

  # Pages routing
  get "/contact" => "contacts#new"
  get "/difficulties" => "difficulty#index"
  get "/:page" => "pages#show"

  # Set root path
  root :to => "pages#show", :page => 'home'
end

app/models/game.rb
class Game < ApplicationRecord
  # Version logging/auditing/changelog
  has_paper_trail

  # Tagging
  acts_as_taggable

  # Search 
  include PgSearch
  multisearchable :against => [:name, :name_alt, :description, :intro, :notes]

  # Relationships
  belongs_to :player

  # Pre-Save Activities
  before_save { self.slug = self.to_slug(self.name) }

  # Validation
  validates_uniqueness_of :name
  validates_uniqueness_of :slug
  validates :name, presence: true
  validates :players_min, presence: true
  validates :players_max, presence: true
  validates :description, presence: true
#  validates :difficulty, presence: true
  validate :players_range

  def to_param
    slug
  end

  private

  def players_range
    unless players_min.nil? || players_max.nil?
      if players_min > players_max
        errors.add(:players_min, "cannot be larger than players max")
      end
      if players_min < 1
        errors.add(:players_min, "cannot be below 1")
      end
      if players_max < 1
        errors.add(:players_max, "cannot be below 1")
      end
    end
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :find_game, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_player!, except: [:index, :show]

  helper_method :get_video_id

  autocomplete :tag, :name, :class_name => "ActsAsTaggableOn::Tag"

  def show
    @title = word_cap(@game.name)
    @players = @game.versions.map { |v| Player.find(v.whodunnit) }.uniq
  end

  def new
    @title = "Add a Game"
    @game = current_player.games.build
    @submit_text = "Create game"
  end

  def edit
    @title = "Edit #{word_cap(@game.name)}"
    @submit_text = "Update game"
  end

  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_path, success: 'Game was successfully deleted.' }
      format.json { render :show, status: :ok, location: @game }
    end
  end
  
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, success: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  def create
    @game = current_player.games.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, success: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  def index
    sort = params[:sort]
    sort = 'name' unless sort.in?(['name', 'players_min', 'players_max'])
    @games = Game.order(sort).paginate(:page => params[:page], :per_page => 20)
    @title = "Games"
  end

  private

  # Never trust internet parameters, whitelist through here
  def game_params
    params.require(:game).permit(:name, :name_alt, :players_min, :players_max, :description, :intro, :notes, :sample, :tag_list, :difficulty_id, :type_id)
  end

  # Locate game by slug
  def find_game
    @game = Game.find_by slug: params[:slug]
    @difficulty = Difficulty.find(@game.difficulty_id)
    ! @game.type_id.nil? ? @type = Type.find(@game.type_id) : @type = ''
  end

  # Strip the video ID from YouTube URLs, compatible with both standard and share URLs
  def get_video_id(url)
    return url.split(/[\/,\=]/).last
  end
end

app/views/games/edit.html.erb
<h2>Editing <%= @game.name %></h2>
<%= form_for(@game) do |f| -%>
    <% if @game.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>
            <ul>
            <% @game.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
            </ul>
        </div>
    <% end %>

    <%= render partial: 'partials/game-form', locals: {f: f} %>

<% end -%>
<% if @game.player == current_player %>
<br>
<h3>Delete Game</h3>
<p>Typo in the game name? Duplicate of an existing game? No worries, just delete!</p>
<%= button_to "Delete Game", game_path(@game), data: { confirm: "Are you sure?" }, method: :delete, class: "btn btn-outline-light" %>
<% end %>

app/views/games/index.html.erb
<h2> Create a Game</h2>
<a class="btn btn-outline-light" href=<%= new_game_path %>>Submit a Game</a>
<hr >
<h2>All Games</h2>
<%= render 'partials/game-list' %>

app/views/games/new.html.erb
<h2>Create Game</h2>

<% if current_player -%>
<%= form_for(@game) do |f| -%>
    <% if @game.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>
            <ul>
            <% @game.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
            </ul>
        </div>
    <% end %>

    <div class="field form-group">
        <%= f.label :name, 'Name' %>
        <%= f.text_field :name, class: "form-control", autofocus: true, required: true %>
    </div>

    <%= render partial: 'partials/game-form', locals: {f: f} %>

<% end -%>
<% else -%>
<p><b>You must be logged in to be able to submit games</b></p>
<%= link_to "Sign up", new_registration_path(:player), class: 'btn btn-outline-light' %>
<%= link_to "Log in", new_session_path(:player), class: 'btn btn-outline-light' %>
<% end -%>

app/views/games/show.html.erb
<h2 style="text-align: center"><%= @title %> <%= link_to 'Edit', edit_game_path, class: "btn btn-outline-light" %></h2>
<% if !@game.name_alt.empty? %><h4 style="text-align: center"><i>Also known as <%= @game.name_alt %></i></h4><% end %>
<p style="text-align: center"><%= render 'partials/social-buttons', locals: {url: @game} %></p>
<hr>
<div class="container-fluid text-center">
    <% @players.each do |player| %><%= link_to( image_tag(player.avatar.attached? ? player.avatar : "profile_image.png", :size => "50x50", :title => player.username, :class => "border border-primary rounded-circle profile_image"), show_player_url(player.username))%>  <% end %>
</div>
<hr>
<div class="container-fluid">
    <div class="row content">
        <div class="col-sm-6 left">
            <p><b>Players:</b> <%= @game.players_min %>-<%= @game.players_max %></p>
            <p><b>Difficulty:</b> <%= link_to word_cap(@difficulty.name), difficulty_path(@difficulty.name) %></p>
        </div>
        <div class="col-sm-6 right">
            <p><b>Type:</b> <% if ! @game.type_id.nil?%><%= link_to word_cap(@type.name), type_path(@type.name) %><% else %>No type <%= link_to "(update the game)", edit_game_path %><% end %></p>
            <p><b>Tags:</b> <%= @game.tag_list.map {|t| link_to word_cap(t), tag_path(t)}.join(", ").html_safe %></p>
        </div>
    </div>
</div>
<ul class="nav nav-tabs" id="myTab" role="tablist">
  <li class="nav-item">
    <a class="nav-link active" id="desc-tab" data-toggle="tab" href="#desc" role="tab" aria-controls="desc" aria-selected="true">Description</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" id="intro-tab" data-toggle="tab" href="#intro" role="tab" aria-controls="intro" aria-selected="false">Intro</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" id="notes-tab" data-toggle="tab" href="#notes" role="tab" aria-controls="notes" aria-selected="false">Notes</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" id="sample-tab" data-toggle="tab" href="#sample" role="tab" aria-controls="sample" aria-selected="false">Sample</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" id="changelog-tab" data-toggle="tab" href="#changelog" role="tab" aria-controls="changelog" aria-selected="false">Changelog</a>
  </li>
</ul>
<div class="tab-content" id="myTabContent">
    <div class="tab-pane fade show active" id="desc" role="tabpanel" aria-labelledby="desc-tab"><%= @game.description.html_safe %></div>
  <div class="tab-pane fade" id="intro" role="tabpanel" aria-labelledby="intro-tab"><%= @game.intro.html_safe.presence || "There doesn't seem to be any info here, consider #{link_to "updating the game", edit_game_path}".html_safe %></div>
  <div class="tab-pane fade" id="notes" role="tabpanel" aria-labelledby="notes-tab"><%= @game.notes.html_safe.presence || "There doesn't seem to be any info here, consider #{link_to "updating the game", edit_game_path}".html_safe %></div>
  <div class="tab-pane fade" id="sample" role="tabpanel" aria-labelledby="sample-tab"><%= render 'partials/video-embed' %></div>
  <div class="tab-pane fade" id="changelog" role="tabpanel" aria-labelledby="changelog-tab"><%= render 'partials/changelog' %></div>
</div>
<% content_for :below do %>
    <%= render 'partials/comments' %>
<% end %>
<%= javascript_tag "tabLinks()" %>